[package]
name = "glazer"
version = "0.1.0"
edition = "2024"

[features]
default = ["opengl", "hot-reload"]
software = ["softbuffer"]
opengl = ["gl", "glutin", "glutin-winit"]
hot-reload = ["libc"]

[dependencies]
cpal = { version = "0.15" }
libc = { version = "0.2", optional = true }
gl = { version = "0.14", optional = true }

[target.'cfg(target_os = "linux")'.dependencies]
winit = { version = "0.30", default-features = false, features = [
	"rwh_06",
	"x11",
] }
softbuffer = { version = "0.4", optional = true, default-features = false, features = [
	"x11",
	"x11-dlopen",
] }
glutin = { version = "0.32", optional = true, default-features = false, features = [
	"egl",
] }
glutin-winit = { version = "0.5", optional = true, default-features = false, features = [
	"egl",
] }


[target.'cfg(target_os = "macos")'.dependencies]
winit = { version = "0.30", default-features = false, features = ["rwh_06"] }
softbuffer = { version = "0.4", optional = true, default-features = false }
glutin = { version = "0.32", optional = true, default-features = false, features = [
	"egl",
] }
glutin-winit = { version = "0.5", optional = true, default-features = false, features = [
	"egl",
] }
